var moneySound = new Audio("./media/money.mp3");
var loserSound = new Audio("./media/loser.mp3");
var slotSound = new Audio("./media/slotmachine.mp3");
    slotSound.volume = .3;
var pullingSound = new Audio("./media/newPull.mp3");
    pullingSound.volume = 1;
var yaySound = new Audio("./media/yay.mp3");
var wowSound = new Audio("./media/wowPerfect.mp3")
    wowSound.volume = 1;
var jackpotSound = new Audio("./media/oh-baby-a-triple.mp3");